SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- Disable constraints
ALTER TABLE CommentReactions NOCHECK CONSTRAINT ALL;
ALTER TABLE Comments NOCHECK CONSTRAINT ALL;
ALTER TABLE Likes NOCHECK CONSTRAINT ALL;
ALTER TABLE ExperienceTags NOCHECK CONSTRAINT ALL;
ALTER TABLE ExperienceImages NOCHECK CONSTRAINT ALL;
ALTER TABLE Experiences NOCHECK CONSTRAINT ALL;
ALTER TABLE ExperienceRatings NOCHECK CONSTRAINT ALL;
ALTER TABLE RatingHelpfuls NOCHECK CONSTRAINT ALL;
ALTER TABLE ExperienceCollaborators NOCHECK CONSTRAINT ALL;
ALTER TABLE SavedExperiences NOCHECK CONSTRAINT ALL;
ALTER TABLE Collections NOCHECK CONSTRAINT ALL;
ALTER TABLE Notifications NOCHECK CONSTRAINT ALL;
ALTER TABLE Follows NOCHECK CONSTRAINT ALL;
ALTER TABLE FollowRequests NOCHECK CONSTRAINT ALL;
ALTER TABLE FollowRequestResponses NOCHECK CONSTRAINT ALL;
ALTER TABLE Messages NOCHECK CONSTRAINT ALL;
ALTER TABLE MessageReactions NOCHECK CONSTRAINT ALL;
ALTER TABLE BlockedUsers NOCHECK CONSTRAINT ALL;
ALTER TABLE StatusViews NOCHECK CONSTRAINT ALL;
ALTER TABLE Statuses NOCHECK CONSTRAINT ALL;
ALTER TABLE DeviceLinks NOCHECK CONSTRAINT ALL;
ALTER TABLE DeviceSessions NOCHECK CONSTRAINT ALL;
ALTER TABLE TripExperiences NOCHECK CONSTRAINT ALL;
ALTER TABLE TripCollaborators NOCHECK CONSTRAINT ALL;
ALTER TABLE Trips NOCHECK CONSTRAINT ALL;
ALTER TABLE GroupMessages NOCHECK CONSTRAINT ALL;
ALTER TABLE GroupMembers NOCHECK CONSTRAINT ALL;
ALTER TABLE GroupChats NOCHECK CONSTRAINT ALL;
ALTER TABLE EventAttendees NOCHECK CONSTRAINT ALL;
ALTER TABLE Events NOCHECK CONSTRAINT ALL;
ALTER TABLE Users NOCHECK CONSTRAINT ALL;
ALTER TABLE Tags NOCHECK CONSTRAINT ALL;
GO

-- Delete from all tables
DELETE FROM CommentReactions;
DELETE FROM Comments;
DELETE FROM Likes;
DELETE FROM ExperienceTags;
DELETE FROM ExperienceImages;
DELETE FROM Experiences;
DELETE FROM ExperienceRatings;
DELETE FROM RatingHelpfuls;
DELETE FROM ExperienceCollaborators;
DELETE FROM SavedExperiences;
DELETE FROM Collections;
DELETE FROM Notifications;
DELETE FROM Follows;
DELETE FROM FollowRequests;
DELETE FROM FollowRequestResponses;
DELETE FROM Messages;
DELETE FROM MessageReactions;
DELETE FROM BlockedUsers;
DELETE FROM StatusViews;
DELETE FROM Statuses;
DELETE FROM DeviceLinks;
DELETE FROM DeviceSessions;
DELETE FROM TripExperiences;
DELETE FROM TripCollaborators;
DELETE FROM Trips;
DELETE FROM GroupMessages;
DELETE FROM GroupMembers;
DELETE FROM GroupChats;
DELETE FROM EventAttendees;
DELETE FROM Events;
DELETE FROM Users WHERE Email != 'admin@wanderly.com';
DELETE FROM Tags;
GO

-- Enable constraints
ALTER TABLE CommentReactions CHECK CONSTRAINT ALL;
ALTER TABLE Comments CHECK CONSTRAINT ALL;
ALTER TABLE Likes CHECK CONSTRAINT ALL;
ALTER TABLE ExperienceTags CHECK CONSTRAINT ALL;
ALTER TABLE ExperienceImages CHECK CONSTRAINT ALL;
ALTER TABLE Experiences CHECK CONSTRAINT ALL;
ALTER TABLE ExperienceRatings CHECK CONSTRAINT ALL;
ALTER TABLE RatingHelpfuls CHECK CONSTRAINT ALL;
ALTER TABLE ExperienceCollaborators CHECK CONSTRAINT ALL;
ALTER TABLE SavedExperiences CHECK CONSTRAINT ALL;
ALTER TABLE Collections CHECK CONSTRAINT ALL;
ALTER TABLE Notifications CHECK CONSTRAINT ALL;
ALTER TABLE Follows CHECK CONSTRAINT ALL;
ALTER TABLE FollowRequests CHECK CONSTRAINT ALL;
ALTER TABLE FollowRequestResponses CHECK CONSTRAINT ALL;
ALTER TABLE Messages CHECK CONSTRAINT ALL;
ALTER TABLE MessageReactions CHECK CONSTRAINT ALL;
ALTER TABLE BlockedUsers CHECK CONSTRAINT ALL;
ALTER TABLE StatusViews CHECK CONSTRAINT ALL;
ALTER TABLE Statuses CHECK CONSTRAINT ALL;
ALTER TABLE DeviceLinks CHECK CONSTRAINT ALL;
ALTER TABLE DeviceSessions CHECK CONSTRAINT ALL;
ALTER TABLE TripExperiences CHECK CONSTRAINT ALL;
ALTER TABLE TripCollaborators CHECK CONSTRAINT ALL;
ALTER TABLE Trips CHECK CONSTRAINT ALL;
ALTER TABLE GroupMessages CHECK CONSTRAINT ALL;
ALTER TABLE GroupMembers CHECK CONSTRAINT ALL;
ALTER TABLE GroupChats CHECK CONSTRAINT ALL;
ALTER TABLE EventAttendees CHECK CONSTRAINT ALL;
ALTER TABLE Events CHECK CONSTRAINT ALL;
ALTER TABLE Users CHECK CONSTRAINT ALL;
ALTER TABLE Tags CHECK CONSTRAINT ALL;
GO

-- Reset identity
DBCC CHECKIDENT('Users', RESEED, 0);
DBCC CHECKIDENT('Experiences', RESEED, 0);
DBCC CHECKIDENT('Comments', RESEED, 0);
DBCC CHECKIDENT('Statuses', RESEED, 0);
DBCC CHECKIDENT('Tags', RESEED, 0);
GO

PRINT 'All tables cleared. Restart application.';
GO

