SET QUOTED_IDENTIFIER ON;
GO

ALTER TABLE CommentReactions NOCHECK CONSTRAINT ALL;
DELETE FROM CommentReactions;
ALTER TABLE Comments NOCHECK CONSTRAINT ALL;
DELETE FROM Comments;
ALTER TABLE Likes NOCHECK CONSTRAINT ALL;
DELETE FROM Likes;
ALTER TABLE ExperienceTags NOCHECK CONSTRAINT ALL;
DELETE FROM ExperienceTags;
ALTER TABLE ExperienceImages NOCHECK CONSTRAINT ALL;
DELETE FROM ExperienceImages;
ALTER TABLE Experiences NOCHECK CONSTRAINT ALL;
DELETE FROM Experiences;
ALTER TABLE Notifications NOCHECK CONSTRAINT ALL;
DELETE FROM Notifications;
ALTER TABLE Follows NOCHECK CONSTRAINT ALL;
DELETE FROM Follows;
ALTER TABLE FollowRequests NOCHECK CONSTRAINT ALL;
DELETE FROM FollowRequests;
ALTER TABLE Messages NOCHECK CONSTRAINT ALL;
DELETE FROM Messages;
ALTER TABLE BlockedUsers NOCHECK CONSTRAINT ALL;
DELETE FROM BlockedUsers;
ALTER TABLE StatusViews NOCHECK CONSTRAINT ALL;
DELETE FROM StatusViews;
ALTER TABLE Statuses NOCHECK CONSTRAINT ALL;
DELETE FROM Statuses;
ALTER TABLE Users NOCHECK CONSTRAINT ALL;
DELETE FROM Users WHERE Email != 'admin@wanderly.com';
ALTER TABLE Tags NOCHECK CONSTRAINT ALL;
DELETE FROM Tags;

ALTER TABLE CommentReactions CHECK CONSTRAINT ALL;
ALTER TABLE Comments CHECK CONSTRAINT ALL;
ALTER TABLE Likes CHECK CONSTRAINT ALL;
ALTER TABLE ExperienceTags CHECK CONSTRAINT ALL;
ALTER TABLE ExperienceImages CHECK CONSTRAINT ALL;
ALTER TABLE Experiences CHECK CONSTRAINT ALL;
ALTER TABLE Notifications CHECK CONSTRAINT ALL;
ALTER TABLE Follows CHECK CONSTRAINT ALL;
ALTER TABLE FollowRequests CHECK CONSTRAINT ALL;
ALTER TABLE Messages CHECK CONSTRAINT ALL;
ALTER TABLE BlockedUsers CHECK CONSTRAINT ALL;
ALTER TABLE StatusViews CHECK CONSTRAINT ALL;
ALTER TABLE Statuses CHECK CONSTRAINT ALL;
ALTER TABLE Users CHECK CONSTRAINT ALL;
ALTER TABLE Tags CHECK CONSTRAINT ALL;

GO

PRINT 'Database cleared. Restart application.';
GO

