@echo off
echo Starting Experience Sharing Application...
echo.
echo Starting Backend Server on port 5029...
start "Backend Server" cmd /k "npm run backend"
echo.
echo Waiting for backend to start...
timeout /t 3 /nobreak >nul
echo.
echo Starting Frontend Server on port 3000...
start "Frontend Server" cmd /k "npm start"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5029/api
echo Frontend: http://localhost:3000
echo.
echo Press any key to exit this window...
pause >nul
